- name: variables from files"
  hosts: web
  vars_files:
  - vars.yml
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hi, Iam learning {{COURSE}}, Duration: {{DURATION}}, Trainer: {{TRAINER}}"